services:
  bot:
    build: ./bot
    container_name: ghostswarm-bot1
    environment:
      - BOT_ID=bigppserver2
      - MQTT_BROKER_URL=mqtt://100.76.233.82:1883
    volumes:
      - /etc/hostname:/host_hostname:ro
    restart: unless-stopped
